### ISSUE TITLE
Kubernetes Worker stops polling work pool

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [PrefectHQ/prefect-kubernetes#106]
# Expectation / Proposal
I sometimes hit an issue where the kubernetes worker is running (deployed using Helm) and it suddenly stops polling the work pool. When I check the pod there is no logs indicating anything went wrong but it simply stops/hangs. It is likely related to https://github.com/PrefectHQ/prefect-kubernetes/issues/96 but not the same.

I'm using AKS witk k8 version 1.27.7

Moved over from https://github.com/PrefectHQ/prefect/issues/11561.

# running the command inside the worker pod

```
Version:             2.14.3
API version:         0.8.4
Python version:      3.11.6
Git commit:          f1ff9257
Built:               Thu, Nov 2, 2023 4:12 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         cloud
```

# Traceback / Example

Sometimes it recovers from the hanging and then I see this in the logs (where it apears that it has been hanging for 10 minuttes)

```
Exception in thread Thread-3 (_replicate_pod_events):
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/response.py", line 761, in _update_chunk_length
    self.chunk_left = int(line, 16)
                      ^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/response.py", line 444, in _error_catcher
    yield
  File "/usr/local/lib/python3.11/site-packages/urllib3/response.py", line 828, in read_chunked
    self._update_chunk_length()
  File "/usr/local/lib/python3.11/site-packages/urllib3/response.py", line 765, in _update_chunk_length
    raise InvalidChunkLength(self, line)
urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.11/site-packages/prefect_kubernetes/events.py", line 93, in _replicate_pod_events
    for event in self._watch.stream(
  File "/usr/local/lib/python3.11/site-packages/kubernetes/watch/watch.py", line 165, in stream
    for line in iter_resp_lines(resp):
  File "/usr/local/lib/python3.11/site-packages/kubernetes/watch/watch.py", line 56, in iter_resp_lines
    for seg in resp.stream(amt=None, decode_content=False):
  File "/usr/local/lib/python3.11/site-packages/urllib3/response.py", line 624, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/usr/local/lib/python3.11/site-packages/urllib3/response.py", line 816, in read_chunked
    with self._error_catcher():
  File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.11/site-packages/urllib3/response.py", line 461, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
22:39:01.985 | ERROR   | prefect.flow_runs.worker - An error occurred while monitoring flow run 'f95bef47-c688-4fd1-85af-aa9177cae6b7'. The flow run will not be marked as failed, but an issue may have occurred.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/response.py", line 761, in _update_chunk_length
    self.chunk_left = int(line, 16)
                      ^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/response.py", line 444, in _error_catcher
    yield
  File "/usr/local/lib/python3.11/site-packages/urllib3/response.py", line 828, in read_chunked
    self._update_chunk_length()
  File "/usr/local/lib/python3.11/site-packages/urllib3/response.py", line 765, in _update_chunk_length
    raise InvalidChunkLength(self, line)
urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/prefect/workers/base.py", line 896, in _submit_run_and_capture_errors
    result = await self.run(
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect_kubernetes/worker.py", line 568, in run
    status_code = await run_sync_in_worker_thread(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/utilities/asyncutils.py", line 91, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect_kubernetes/worker.py", line 841, in _watch_job
    for event in watch.stream(
  File "/usr/local/lib/python3.11/site-packages/kubernetes/watch/watch.py", line 165, in stream
    for line in iter_resp_lines(resp):
  File "/usr/local/lib/python3.11/site-packages/kubernetes/watch/watch.py", line 56, in iter_resp_lines
    for seg in resp.stream(amt=None, decode_content=False):
  File "/usr/local/lib/python3.11/site-packages/urllib3/response.py", line 624, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/usr/local/lib/python3.11/site-packages/urllib3/response.py", line 816, in read_chunked
    with self._error_catcher():
  File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.11/site-packages/urllib3/response.py", line 461, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
```
- [ ] I would like to [help contribute](https://PrefectHQ.github.io/prefect-kubernetes/#contributing) a pull request to resolve this!

**Comment by thomasfrederikhoeck** [comment]
Sometimes the Worker manage to start picking up flows again but we just experinced that it keept hanging and hasn't picked up flows for 2+ hours resulting in all our flows being late.... @urimandujano 

Ping at @emilrex : just wanted to let you know what might be the same as https://github.com/PrefectHQ/prefect-kubernetes/issues/96 is giving us quite server problems. It didn't really happen when we had a few deployments but yesterday we migrated all our flows from 1.x to 2.x and the problem really started to pick up.. :-/

**Comment by thomasfrederikhoeck** [comment]
As a very crude way to hack around it you can set up a k8 CronJob which deletes the worker pod every 15 min so you know that at the latest they are 15 min late. But not very ideal.


```yaml
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: prefect-worker-deleter
  namespace: prefect-p
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          serviceAccountName: prefect-worker-deleter
          containers:
          - name: prefect-worker-deleter
            image: bitnami/kubectl:1.25.11
            command: ["/bin/sh", "-c"]
            args:
            - kubectl delete pods -l app.kubernetes.io/name=prefect-worker -n prefect-p
          restartPolicy: OnFailure
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: prefect-p
  name: prefect-worker-deleter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: prefect-p
  name: prefect-worker-deleter
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prefect-worker-deleter
  namespace: prefect-p
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prefect-worker-deleter
subjects:
- kind: ServiceAccount
  name: prefect-worker-deleter
  namespace: prefect-p
```

**Comment by thomasfrederikhoeck** [comment]
This would be solved by #107 when a new release is done (including new Docker images)

**Comment by urimandujano** [comment]
Thanks for taking the fix out for a test run so quickly, this is an unfortunate result. Do we have anymore data to work with? I would expect the specific errors above to not be showing up anymore and there were a few places where we tackled broken or disconnected log streams. Has there been any change in worker behavior?

**Comment by walter-cavinaw** [comment]
We are experiencing the same issue. Worked fine when we had a small number of flows test running the new worker (moving over from prefect agent). But now with hundreds of flows running, often dozens running at a time, the worker eventually stops polling. Our worker has not recovered in any of these instances and we don't have any error logs.

**Comment by maitlandmarshall** [comment]
All my deployments are failing with the "Pod never started", but Prefect marks the flow run as Green Completed
![image](https://github.com/PrefectHQ/prefect-kubernetes/assets/38200645/3714e472-23d4-4bd6-87e2-bc1b3fc64990)

**Comment by thomasfrederikhoeck** [comment]
@urimandujano I have send some more logs through to Kevin on your end.

@walter-cavinaw are you also using AKS? From https://learn.microsoft.com/en-us/azure/load-balancer/load-balancer-tcp-idle-timeout?tabs=tcp-reset-idle-portal

> “By default, it's set to 4 minutes. If a period of inactivity is longer than the timeout value, there's no guarantee that the TCP or HTTP session is maintained between the client and your service.”

I don't know if it is related to the worker having many threads which queries the K8 API but then end up being not used for 4 min, and then at some point going stale, and then in the end all threads are blocked with stale connections.

See following GH issues where we faced a similar is issue in Prefect 1.x:
https://github.com/PrefectHQ/prefect/pull/3344
https://github.com/Azure/AKS/issues/1052
https://github.com/Azure/AKS/issues/1755

**Comment by brandonwissmann** [comment]
@walter-cavinaw Yes, reverting to 2.14.15 resolved all our issues in regards to this. There is another issue where it is not closing connections so we are also restarting the workers every few days on a schedule before it reaches the limit.  (#102)

**Comment by OliverKleinBST** [comment]
We have a similar problem, and its pretty reproducible. Once we have scheduled flows and flows that run like about 5 minutes we quickly see that the workpool gets in state unhealthy - and we need to restart the worker pod to get it back alive. Also nothing visible in the logs. We see this after migration from agents to workers which we did on 2.14.5. An upgrade to 2.14.15 did not make any difference to us.

**Comment by OliverKleinBST** [comment]
Unfortunately, after more testing, it seems still not be reliable.
We had more events where it went into disconnect, but then was able to reconnect sometimes quickly sometimes after some minutes - without restart. But then also got situations where it does not recover at all.

**Comment by OliverKleinBST** [comment]
@thomasfrederikhoeck Do you have a link to the prefect 1.x solution?

Meanwhile we follow the cron job approach, but adjust it a bit to query the server API if the workpool is reporting "NOT_READY" and only then delete the pod.

```
url=${PREFECT_API_URL}'/work_pools/default-workpool'
res=$(wget -qO- "$url")
status=$(echo "$res" | grep -o '"status":[^,}]*' | awk -F'"' '{print $4}')

if [ "$status" = "NOT_READY" ]; then
    echo "Status is $status. Running kubectl command..."
    kubectl delete pods -l app.kubernetes.io/name=prefect-worker -n prefect-p
fi
```

**Comment by urimandujano** [comment]
I think we have a grip on what's going on and we're working on a couple of fixes to `prefect-kubernetes`. For now, anyone using the helm chart should pin the helm chart they're using to avoid `prefect-kubernetes v0.3.3` (which are [2024.1.30](https://github.com/PrefectHQ/prefect-helm/releases/tag/2024.1.30) and [2024.1.25](https://github.com/PrefectHQ/prefect-helm/releases/tag/2024.1.25)) and anyone directly using `prefect-kubernetes` based worker processes should avoid v0.3.3. We're currently working to include the fix in today's release!

**Comment by urimandujano** [comment]
We just rolled out release `prefect-kubernetes v0.3.4` and released helm chart `v2024.2.1` which bundles the new `prefect-kubernetes` release with `prefect v2.14.19`. We expect this release to address the issue so please try it out at your convenience. In the meantime, I'll leave this open for feedback if issues persist.

**Comment by thomasfrederikhoeck** [comment]
@urimandujano  @kevingrismore We have used the new image and it has been running smoothly for 6 hours now!! 🎉🎉🎉

**Comment by OliverKleinBST** [comment]
same for mw :-)
