### ISSUE TITLE
multi run_namespaced_job funcs run togeter. If a job error ,others job will get error.

### ISSUE THREAD

**Issue by nextvirus** [PrefectHQ/prefect-kubernetes#65]
Code like this :
```
for i in job:
    log = run_namespaced_job(i)
```
If one job faild , the def wait_for_completion()  of the jobs.py , self._completed  = False , it counldn't become self._completed = True. this while will continue. Then it will get a error and retry the same job. But if it didn't delete the job , the kuberentes will get error like this `HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"jobs.batch \"bidding-hunter-cjwiif\" already exists","reason":"AlreadyExists","details":{"name":"bidding-hunter-cjwiif","group":"batch","kind":"jobs"},"code":409}`

# Traceback / Example
Temporary fix this issues, i modify the jobs.py. Let the program exit , then it can run the other jobs
- [ ] I would like to [help contribute](https://PrefectHQ.github.io/prefect-kubernetes/#contributing) a pull request to resolve this!

**Comment by nextvirus** [comment]
`self._completed = True
self.logger.info(
    f"Job {v1_job_status.metadata.name!r} failed, check the "
    "Kubernetes pod logs for more information."
)
# raise RuntimeError(
#     f"Job {v1_job_status.metadata.name!r} failed, check the "
#     "Kubernetes pod logs for more information."
# )`
#58

**Comment by desertaxle** [comment]
I'm sorry for the delay. I'm having trouble understanding what the issue is. I'm going to assume this issue is stale and close it. Please reopen with more details if the issue persists.
