### ISSUE TITLE
Support entirety of KubernetesJob Spec out of the box

### ISSUE THREAD

**Issue by marcm-ml** [PrefectHQ/prefect-kubernetes#84]
Hello,

I found myself in the place that I basically have to write a worker and thus infrastructure block from scratch just to support the whole range of the KubernetesJob spec. I think this should be the default and I don't understand why the decision has been made to limit this library to only a very limited subset of options such as env, args, labels, name... Much of the flexibility of kubernetes is lost due to that, e.g. we cannot map secrets to the pod as environment variables, see #83.

# Expectation / Proposal

I propose to add all the available options from the KubernetesJob spec to the `KubernetesWorkerVariables`, `KubernetesWorkerJobConfiguration` and `KubernetesJob` classes. I already did the majority of the work for myself and are happy to create a PR for this.

# Traceback / Example

For example, the version of my `KubernetesWorkerVariables` used in my custom worker is simply extending the current class:

```python

class KASWorkerVariables(KubernetesWorkerVariables):
    ports: list[Port] | None = Field(
        default=None,
        description="Ports exposed on the container",
    )
    labels: dict[str, str] | None = Field(
        default=_get_default_labels(),
        description="Container labels",
    )
    command: list[str] | None = Field(
        default=None,
        description="Container command",
    )
    args: list[str] | None = Field(
        default=None,
        description="Container arguments appended to container command",
    )
    volumes: list[Volume] | None = Field(
        default=None,
        description="List of volumes to expose",
    )
    affinity: Affinity | None = Field(
        default=None,
        description="Pod Affinity",
    )
    env_from: list[EnvRef] | None = Field(
        default=None,
        description="Kubernetes References that are mapped as environment variables in the KubernetesJob",
    )
    resources: Resources | None = Field(
        default=Resources(
            limits=Resource(memory="2Gi"),
            requests=Resource(cpu="1", memory="2Gi"),
        ),
        description="Pod Kubernetes Ressources",
    )
    annotations: dict[str, str] | None = Field(
        default=None,
        description="Pod's annotation",
    )
    volume_mounts: list[VolumeMount] | None = Field(
        default=None,
        description="List of volumes to mount into the pod",
    )
    image_pull_secrets: list[ImagePullSecret] | None = Field(
        default=[ImagePullSecret(name="my-pull-secret")],
        description="List of image pull secrets",
    )
```

You can see that in non-trivial cases I added Pedantic Models that mimmic the KubernetesJob spec, such as Resources, Port, Volume, VolumeMount, EnvRef, Affinity

- [x] I would like to [help contribute](https://PrefectHQ.github.io/prefect-kubernetes/#contributing) a pull request to resolve this!

**Comment by desertaxle** [comment]
Thanks for opening an issue @marcm-ml! The Kubernetes worker currently supports the full Kubernetes Job spec. The `KubernetesWorkerVariables` class represents the default variables to use for the Kuberentes worker's base job template, but this template can be changed for a given work pool in the Prefect UI, and it shouldn't be necessary to create a new worker type or variables class to add or remove fields in the manifest. 

You can find an example of extending the default templated manifest uses at the top of [this page in the docs](https://prefecthq.github.io/prefect-kubernetes/worker/). 

I'm going to close this issue because I don't think any development is necessary to support this use case, but feel free to post any questions that you have on this issue!

**Comment by marcm-ml** [comment]
I understand that. It would be nice to have the job template already as flexibel as possible imho. I think this would benefit most users and would not really complicate the Worker by much. You would not lose any functionality and would also not break existing setup. All you provide is more ways to configure Kubernetes jobs out of the box.

On another note:
If I want to have our Prefect setup written entirely as Infrastructue-as-Code, I need a way to make this happen programmatically. I see only two ways (please correct me if there are other ways too): 


1. creating a base job template by hand and using the prefect client to create or update the work pool. You can get the template also by writing the worker code and using a build in method to get the template through code. This does not required you to deploy the worker.

2. Write a custom worker to start my custom work pool with the job template. By leveraging the workers ability to create work pool out of the box.


As you have pointed out, it is not necessary to write a worker. Any custom template can be used with the kubernetes worker. However, it is the manual part of changing it in the UI that bothers me the most. I would prefer if the worker would provide such a flexible base job template out of the box. This is also what I expected when I first looked into it and it took me quite some time to figure out why it works the way it does. Coming from the kubernetes world this was very unintuitive.
